### ISSUE TITLE
Binary file within `agree.c`

### ISSUE THREAD

**Issue by Sigmanificient** [kyu08/cs50#1]
Hi, I saw your `CS-50` repository and wanted to take a look at the sources.
Seems like `agree.c` contains binary from a compiled file, just want to make sure that you are aware of it.

Wish you the best!

**Comment by kyu08** [comment]
@Sigmanificient 
Hi! Thanks for your interest in my repo. 😄
I think I accidentally specified `agree.c` as the compile output destination. But I don't need it anymore, so I will delete the binary file.
